reports: -p base
default: -p base -e routes_report.rb
base:  -r features --format pretty --format rerun --out tmp/rerun.txt --tags=~@upcoming --tags=~@old-ui
rerun: "-r features @tmp/rerun.txt --format pretty --format rerun --out tmp/rererun.txt"
